package com.ogtrz.hazuki.ui.theme.colorscheme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/*
 * Colors for Default theme
 * M3 colors generated by Material Theme Builder (https://material-foundation.github.io/material-theme-builder/)
 *
 * High contrast option with color match activated
 * Key colors:
 * Primary #A4515D
 * Secondary #A4515D
 * Tertiary #B58672
 */
internal object HazukiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFEBEC),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0xFFFFACB5),
        onPrimaryContainer = Color(0xFF210005),

        secondary = Color(0xFFFFEBEC),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xFFFFACB5),
        onSecondaryContainer = Color(0xFF210005),

        tertiary = Color(0xFFFFECE5),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFFEBB7A1),
        onTertiaryContainer = Color(0xFF1B0500),

        error = Color(0xFFFFECE9),
        onError = Color(0xFF000000),
        errorContainer = Color(0xFFFFAEA4),
        onErrorContainer = Color(0xFF220001),

        background = Color(0xFF191112),
        onBackground = Color(0xFFEEDFDF),

        surface = Color(0xFF191112),
        onSurface = Color(0xFFFFFFFF),

        surfaceVariant = Color(0xFF544244),
        onSurfaceVariant = Color(0xFFFFFFFF),

        outline = Color(0xFFFFEBEC),
        outlineVariant = Color(0xFFD5BDBE),

        scrim = Color(0xFF000000),

        inverseSurface = Color(0xFFEEDFDF),
        inverseOnSurface = Color(0xFF000000),
        inversePrimary = Color(0xFF792F3C),

        surfaceDim = Color(0xFF191112),
        surfaceBright = Color(0xFF584E4E),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF1A1414),
        surfaceContainer = Color(0xFF262122),
        surfaceContainerHigh = Color(0xFF43393A),
        surfaceContainerHighest = Color(0xFF4E4445),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF551321),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF7B303D),
        onPrimaryContainer = Color(0xFFFFFFFF),

        secondary = Color(0xFF551321),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF7B303D),
        onSecondaryContainer = Color(0xFFFFFFFF),

        tertiary = Color(0xFF442415),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF654030),
        onTertiaryContainer = Color(0xFFFFFFFF),

        error = Color(0xFF600004),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF98000A),
        onErrorContainer = Color(0xFFFFFFFF),

        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF211A1A),

        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF000000),

        surfaceVariant = Color(0xFFF6DCDE),
        onSurfaceVariant = Color(0xFF000000),

        outline = Color(0xFF37282A),
        outlineVariant = Color(0xFF564546),

        scrim = Color(0xFF000000),

        inverseSurface = Color(0xFF372E2F),
        inverseOnSurface = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFFFB2BA),

        surfaceDim = Color(0xFFC4B5B6),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFDEDED),
        surfaceContainer = Color(0xFFEEDFDF),
        surfaceContainerHigh = Color(0xFFE0D1D1),
        surfaceContainerHighest = Color(0xFFD2C3C3),
    )
}